addSbtPlugin("com.typesafe.sbt" % "sbt-web-build-base" % "1.2.3")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.3")
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.4")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.12")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.1")
